Vagrant.configure(2) do |config|
  config.vm.box = "opscode-ubuntu-14.10"

  config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.10_chef-provisionerless.box"

  config.omnibus.chef_version = "11.16.4"

  config.vm.provision :chef_client do |chef|
    chef.chef_server_url = "https://chef-cl.nisum.com/"
    chef.validation_key_path = "./.chef/validation.pem"
    chef.node_name = "rgonzalezNode"
  end

end
