---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4

platforms:
  - name: centos-6.6
    driver_config:
      network:
      - ["private_network", {ip: "77.77.77.70"}]

suites:
  - name: default
    run_list:
      - recipe[rgLoadBalancer::default]
    attributes: