---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4

platforms:
  - name: centos-6.6
    driver_config:
      network:
      - ["private_network", {ip: "33.33.33.41"}]
  - name: ubuntu-14.10
    driver_config:
        network:
        - ["private_network", {ip: "33.33.33.42"}]

suites:
  - name: default
    run_list:
      - recipe[rgCookbook::default]
    attributes:
  - name: webServer
    run_list:
      - recipe[rgCookbook::rgWebServer]
    attributes:
    attributes:
  - name: loadBalancer
    run_list:
      - recipe[rgCookbook::rgLoadBalancer]
    attributes:    
