---
driver:
  name: vagrant
  require_chef_omnibus: 11.16.4

provisioner:
  name: chef_solo

platforms:
  - name: opscode-ubuntu-14.10
    driver:
      box: opscode-ubuntu-14.10
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.10_chef-provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[rgonzalez-cookbook::default]
    attributes:
